# Generated by Django 2.1.2 on 2019-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('published', models.DateField(blank=True, verbose_name='投稿日')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='画像')),
                ('body', models.TextField(verbose_name='本文')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
